### PR TITLE
try to fix github.com/vuejs/vue/issues/6353

### PR DESCRIPTION
**Pull request by JounQin**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
No

**If relevant, did you update the README?**
No

**Summary**
add `_renderStyles` property on context, so that we could define `styles` property in `vue-server-renderer`

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by yyx990803** [comment]
see https://github.com/vuejs/vue/pull/6522#issuecomment-329056170

**Comment by yyx990803** [comment]
Sorry, your original fix idea was better... I introduced a regression in my fix. Should've merged yours instead :)

**Comment by JounQin** [comment]
Would you like to explain what's wrong with your original fix?

**Comment by yyx990803** [comment]
The original fix was checking the presence of `context.styles` too early. At that point, only the root app instance has been created and the renderer hasn't started rendering the entire component tree yet, so no lifecycle styles would have been injected at that point. Creating `context.styles` there actually prevents `vue-style-loader` from creating it later, causing all lifecycle styles to be lost.

**Pull request closed without merging**
